name: Build and Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image for community service
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/community
          push: true
          tags: fjaesbog.azurecr.io/community:${{ github.sha }}

      - name: Build and push Docker image for email service
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/email
          push: true
          tags: fjaesbog.azurecr.io/email:${{ github.sha }}

      - name: Build and push Docker image for posts service
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/posts
          push: true
          tags: fjaesbog.azurecr.io/posts:${{ github.sha }}

      - name: Build and push Docker image for reactions service
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/reactions
          push: true
          tags: fjaesbog.azurecr.io/reactions:${{ github.sha }}

      - name: Build and push Docker image for user service
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/user
          push: true
          tags: fjaesbog.azurecr.io/user:${{ github.sha }}

      - name: Build and push Docker image for gateway service
        uses: docker/build-push-action@v2
        with:
          context: ./microservices/gateway
          push: true
          tags: fjaesbog.azurecr.io/gateway:${{ github.sha }}

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az webapp config container set --name community --resource-group fjaesbog --docker-custom-image-name fjaesbog.azurecr.io/community:${{ github.sha }} --docker-registry-server-url https://fjaesbog.azurecr.io --docker-registry-server-user myregistry --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}
            az webapp config container set --name email --resource-group fjaesbog --docker-custom-image-name fjaesbog.azurecr.io/email:${{ github.sha }} --docker-registry-server-url https://fjaesbog.azurecr.io --docker-registry-server-user myregistry --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}
            az webapp config container set --name posts --resource-group fjaesbog --docker-custom-image-name fjaesbog.azurecr.io/posts:${{ github.sha }} --docker-registry-server-url https://fjaesbog.azurecr.io --docker-registry-server-user myregistry --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}
            az webapp config container set --name reactions --resource-group fjaesbog --docker-custom-image-name fjaesbog.azurecr.io/reactions:${{ github.sha }} --docker-registry-server-url https://fjaesbog.azurecr.io --docker
